---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.5
    driver:
      box: chef/centos-6.5
      network:
      - ["private_network", {ip: "192.168.33.10"}]
      customize:
        cpus: 2
        memory: 2048

suites:
  - name: default
    run_list:
      - recipe[blog::default]
    attributes:
